#!/usr/bin/env python3
"""
Regenerates supabase/combined/FRESH_INSTALL.sql and APPLY_ALL.sql from the
individual migration files in supabase/migrations/, in timestamp order.

Usage (via the shell wrapper):
    ./scripts/build-combined-sql.sh           # build / overwrite
    ./scripts/build-combined-sql.sh --check   # exit 1 if files are out of date

Called directly:
    python3 scripts/build-combined-sql.py --repo-root /path/to/repo [--check]

──────────────────────────────────────────────────────────────────────────────
APPLY_ALL eligibility
──────────────────────────────────────────────────────────────────────────────
Only migrations that are both "operational" (timestamp >= 20260811, i.e. the
privilege-lockdown wave) AND idempotent (safe to rerun) are included in
APPLY_ALL.sql.

To mark a migration as non-idempotent, add the following comment anywhere in
the first 10 lines of the file:

    -- @apply-all: skip

Any migration bearing that marker is excluded from APPLY_ALL.sql but still
included in FRESH_INSTALL.sql (which is run exactly once on an empty database).

──────────────────────────────────────────────────────────────────────────────
FRESH_INSTALL transforms
──────────────────────────────────────────────────────────────────────────────
Three per-migration transforms are applied when building FRESH_INSTALL.sql:

  1. Migration 20260323141545_*  — expand the trade_status enum to include
     'locked' and 'expired' (added later via ALTER TYPE; not usable in the
     same transaction after ADD VALUE).

  2. Migration 20260323143411_*  — suppress the ALTER TYPE ADD VALUE lines
     that add 'locked'/'expired' (already folded into transform #1).

  3. Migration 20260323143733_*  — wrap bare CREATE EXTENSION calls in a
     DO block so an unavailable extension cannot abort the install.

──────────────────────────────────────────────────────────────────────────────
Shared transforms (FRESH_INSTALL + APPLY_ALL)
──────────────────────────────────────────────────────────────────────────────
  4. Migration 20260816150000_*  — wrap cron.unschedule / cron.schedule calls
     in a DO block that checks pg_extension for pg_cron availability, so the
     script continues gracefully when pg_cron is not installed.
"""
import argparse
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Static file headers
# ---------------------------------------------------------------------------

FRESH_INSTALL_HEADER = """\
-- =========================================================================
-- P2PxBT -- FRESH INSTALL
-- =========================================================================
-- Every migration in the repository, in order, for a BRAND NEW and EMPTY
-- Supabase project.
--
-- RUN THIS ONLY ON AN EMPTY PROJECT. The original migrations use bare
-- CREATE TABLE / CREATE POLICY and will error on a database that already
-- has this schema. For a project that already has the original tables, use
-- APPLY_ALL.sql instead -- that contains only the operational layer and is
-- idempotent.
--
-- Two deviations from the raw migration history, both required to make this
-- runnable as a single transaction:
--   * trade_status is created with its full value list up front. The history
--     added locked/expired later via ALTER TYPE ... ADD VALUE, which cannot
--     be followed by a use of the new value in the same transaction.
--   * CREATE EXTENSION for pg_cron/pg_net is wrapped so an unavailable
--     extension cannot abort the install.
--
-- After running, grant yourself the operator role:
--
--   insert into public.user_roles (user_id, role)
--   select id, 'admin' from auth.users where email = 'you@example.com'
--   on conflict (user_id, role) do nothing;
--
-- Generated from supabase/migrations/ -- do not edit directly.
-- =========================================================================\
"""

APPLY_ALL_HEADER_TMPL = """\
-- =========================================================================
-- P2PxBT Demo -- COMBINED MIGRATION
--
-- {count} operational migration(s) concatenated in dependency order, so this
-- can be run as a single paste in the Supabase SQL editor.
--
-- Generated from supabase/migrations/ -- do not edit this file directly;
-- edit the individual migrations and regenerate.
--
-- Every statement is idempotent (IF NOT EXISTS / DROP POLICY IF EXISTS /
-- ON CONFLICT), so re-running the whole file is safe.
--
-- Migrations marked  -- @apply-all: skip  in their source file are excluded
-- because they contain non-idempotent data-seeding statements (e.g. random()).
-- =========================================================================\
"""

# ---------------------------------------------------------------------------
# APPLY_ALL eligibility marker
# ---------------------------------------------------------------------------
_SKIP_MARKER = "-- @apply-all: skip"
_OPERATIONAL_CUTOFF = "20260811"  # filename prefix; migrations before this are base schema only


def is_apply_all_eligible(migration_path: Path) -> bool:
    """Return True iff this migration should appear in APPLY_ALL.sql."""
    if migration_path.name < _OPERATIONAL_CUTOFF:
        return False
    # Read only the first 15 lines to check for the opt-out marker.
    try:
        with migration_path.open(encoding="utf-8") as f:
            for i, line in enumerate(f):
                if i >= 15:
                    break
                if _SKIP_MARKER in line:
                    return False
    except OSError:
        pass
    return True


# ---------------------------------------------------------------------------
# Per-migration content transforms
# ---------------------------------------------------------------------------

# ── Transform 1: expand trade_status enum (FRESH_INSTALL only) ────────────

def transform_migration1(content: str) -> str:
    old = "ENUM ('pending', 'paid', 'completed', 'disputed', 'cancelled')"
    new = "ENUM ('pending', 'paid', 'completed', 'disputed', 'cancelled', 'locked', 'expired')"
    return content.replace(old, new)


# ── Transform 2: suppress ALTER TYPE ADD VALUE lines (FRESH_INSTALL only) ─

def transform_migration2(content: str) -> str:
    lines_to_drop = {
        "-- Extend trade_status enum with 'locked' and 'expired'",
        "ALTER TYPE public.trade_status ADD VALUE IF NOT EXISTS 'locked';",
        "ALTER TYPE public.trade_status ADD VALUE IF NOT EXISTS 'expired';",
    }
    result_lines: list[str] = []
    comment_inserted = False
    for line in content.splitlines(keepends=True):
        stripped = line.rstrip("\n").rstrip("\r")
        if stripped in lines_to_drop:
            if not comment_inserted:
                result_lines.append(
                    "-- (locked/expired are folded into the CREATE TYPE above for fresh installs)\n"
                )
                comment_inserted = True
            # skip original line
        else:
            result_lines.append(line)
    return "".join(result_lines)


# ── Transform 3: wrap pg_cron/pg_net extension creation (FRESH_INSTALL only)

MIGRATION3_REPLACEMENT = """\
DO $ext$
BEGIN
  BEGIN CREATE EXTENSION IF NOT EXISTS pg_cron WITH SCHEMA pg_catalog;
  EXCEPTION WHEN OTHERS THEN RAISE NOTICE 'pg_cron not enabled: %', SQLERRM; END;
  BEGIN CREATE EXTENSION IF NOT EXISTS pg_net WITH SCHEMA extensions;
  EXCEPTION WHEN OTHERS THEN RAISE NOTICE 'pg_net not enabled: %', SQLERRM; END;
END
$ext$;
"""

# ── Transform 4: guard cron scheduling behind pg_cron availability check ───
# Applied to both FRESH_INSTALL and APPLY_ALL.
#
# The raw migration uses:
#   SELECT cron.unschedule(...) WHERE EXISTS (...);
#   SELECT cron.schedule(...);
#
# These will error if pg_cron is not installed. We wrap them in a DO block
# that first checks pg_extension so the rest of the migration can proceed.

_CRON_RAW_BLOCK = """\
SELECT cron.unschedule('expire-overdue-demo-trades') WHERE EXISTS (
  SELECT 1 FROM cron.job WHERE jobname = 'expire-overdue-demo-trades'
);

SELECT cron.schedule(
  'expire-overdue-demo-trades',
  '* * * * *',   -- every minute
  $$SELECT public.expire_overdue_demo_trades();$$
);\
"""

_CRON_GUARDED_BLOCK = """\
DO $cron_guard$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
    IF EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'expire-overdue-demo-trades') THEN
      PERFORM cron.unschedule('expire-overdue-demo-trades');
    END IF;
    PERFORM cron.schedule(
      'expire-overdue-demo-trades',
      '* * * * *',
      $$SELECT public.expire_overdue_demo_trades();$$
    );
  ELSE
    RAISE NOTICE 'pg_cron not available -- expire-overdue-demo-trades job not scheduled';
  END IF;
END
$cron_guard$;\
"""


def transform_migration_expiry(content: str) -> str:
    """Wrap cron scheduling calls so pg_cron absence is non-fatal."""
    return content.replace(_CRON_RAW_BLOCK, _CRON_GUARDED_BLOCK)


# ---------------------------------------------------------------------------
# Apply transforms per migration
# ---------------------------------------------------------------------------

def apply_fresh_install_transforms(filename: str, content: str) -> str:
    if filename.startswith("20260323141545_"):
        content = transform_migration1(content)
    elif filename.startswith("20260323143411_"):
        content = transform_migration2(content)
    elif filename.startswith("20260323143733_"):
        content = MIGRATION3_REPLACEMENT
    # cron guard applies in addition to any other fresh-install transform
    if filename.startswith("20260816150000_"):
        content = transform_migration_expiry(content)
    return content


def apply_apply_all_transforms(filename: str, content: str) -> str:
    if filename.startswith("20260816150000_"):
        content = transform_migration_expiry(content)
    return content


# ---------------------------------------------------------------------------
# Section header
# ---------------------------------------------------------------------------

SECTION_DIVIDER = "-- #########################################################################"


def section_header(filename: str) -> str:
    return f"\n{SECTION_DIVIDER}\n-- ## {filename}\n{SECTION_DIVIDER}\n"


# ---------------------------------------------------------------------------
# Builders
# ---------------------------------------------------------------------------

def build_fresh_install(migrations: list[Path]) -> str:
    parts = [FRESH_INSTALL_HEADER]
    for mig in migrations:
        raw = mig.read_text(encoding="utf-8")
        content = apply_fresh_install_transforms(mig.name, raw)
        parts.append(section_header(mig.name))
        parts.append("\n")
        parts.append(content)
        if not content.endswith("\n"):
            parts.append("\n")
    return "".join(parts) + "\n"


def build_apply_all(operational_migrations: list[Path]) -> str:
    count = len(operational_migrations)
    parts = [APPLY_ALL_HEADER_TMPL.format(count=count)]
    for mig in operational_migrations:
        raw = mig.read_text(encoding="utf-8")
        content = apply_apply_all_transforms(mig.name, raw)
        parts.append(section_header(mig.name))
        parts.append("\n")
        parts.append(content)
        if not content.endswith("\n"):
            parts.append("\n")
    return "".join(parts) + "\n"


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", required=True)
    parser.add_argument("--check", action="store_true",
                        help="Exit 1 if combined files are out of date")
    args = parser.parse_args()

    repo_root = Path(args.repo_root)
    migrations_dir = repo_root / "artifacts/trust-escrow-flow/supabase/migrations"
    combined_dir   = repo_root / "artifacts/trust-escrow-flow/supabase/combined"

    if not migrations_dir.is_dir():
        print(f"ERROR: migrations directory not found: {migrations_dir}", file=sys.stderr)
        return 1

    all_migrations = sorted(migrations_dir.glob("*.sql"))
    if not all_migrations:
        print("ERROR: no migration files found", file=sys.stderr)
        return 1

    operational_migrations = [m for m in all_migrations if is_apply_all_eligible(m)]

    fresh_content = build_fresh_install(all_migrations)
    apply_content = build_apply_all(operational_migrations)

    fresh_path = combined_dir / "FRESH_INSTALL.sql"
    apply_path = combined_dir / "APPLY_ALL.sql"

    if args.check:
        errors: list[str] = []

        def check_file(path: Path, generated: str) -> None:
            if not path.exists():
                errors.append(f"MISSING: {path.relative_to(repo_root)}")
                return
            on_disk = path.read_text(encoding="utf-8-sig")  # strips BOM if present
            if on_disk != generated:
                errors.append(
                    f"OUT OF DATE: {path.relative_to(repo_root)}\n"
                    "  Run `pnpm build:sql` to regenerate."
                )

        check_file(fresh_path, fresh_content)
        check_file(apply_path, apply_content)

        if errors:
            for e in errors:
                print(e, file=sys.stderr)
            return 1

        print("✓ Combined SQL files are up to date.")
        return 0

    # Write mode
    combined_dir.mkdir(parents=True, exist_ok=True)
    fresh_path.write_text(fresh_content, encoding="utf-8")
    apply_path.write_text(apply_content, encoding="utf-8")

    skipped = [m for m in all_migrations
               if m.name >= _OPERATIONAL_CUTOFF and not is_apply_all_eligible(m)]
    if skipped:
        print(f"  (excluded from APPLY_ALL — @apply-all: skip: "
              f"{', '.join(m.name for m in skipped)})")

    print(f"✓ FRESH_INSTALL.sql  ({len(all_migrations)} migrations)")
    print(f"✓ APPLY_ALL.sql      ({len(operational_migrations)} operational migrations)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
